version: "3.2"
services:
  flask:
    build: .
    image: barcode-google-search
    ports:
       - "9090:${PORT:-8080}"
    environment:
     # /run/docs/reference/container-contract
     PORT: ${PORT:-8080}
     K_SERVICE: sample-app
     K_REVISION: 0
     K_CONFIGURATION: sample-app 